services:
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER:  ${POSTGRES_USER}
      POSTGRES_DB:  ${POSTGRES_DB}
      POSTGRES_HOST:  ${POSTGRES_HOST}
    env_file:
      - .env
    ports:
      - '5432:5432'